# Site settings
title: HOW IS THE AIR IN BEIJING NOW?
description: > # HOW IS THE AIR IN BEIJING NOW?
author: Yang Wang
baseurl: "/HowIsBeijing-sSmog" # the subpath of your site, e.g. /blog/
url: "http://yangwang.info" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
