# Site settings
title: How is the smog right now?
description: > # How is the smog in Beijing right now?
baseurl: "/HowIsBeijing-sSmog" # the subpath of your site, e.g. /blog/
url: "http://yangwang.info" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
